[package]
name = "srvpru"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
parking_lot = { version = "0.11", features=["send_guard"] }
downcast-rs = "1.2.0"
lazy_static = "1.4.0"
once_cell = "1.8.0"
encoding_rs = "0.8.28"
num_enum = "0.5.4"
tokio = { version = "1.11.0", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
serde-big-array = "0.3.2"
erased-serde = "0.3.16"
bincode = "1"
serde_json = "1.0"
log = "0.4"
pretty_env_logger = "0.4.0"