[package]
name = "scanner"
version = "0.1.0"
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.10"
syn = { version = "1.0.80", features = ["full"] }
proc-macro2 = "1.0.29"
proc-macro-error = "1.0.4"