[package]
name = "srvpro"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-stream = { version = "0.1", features = ["sync"] }
tokio-util = { version = "0.7", features = ["codec"] }
anymap3 = { version = "1", default-features = false, features = ["hashbrown"] }
hashbrown = { version = "0.17", features = ["serde"] }
chrono = { version = "0.4", features = ["clock"] }
slab = "0.4.12"
arc-swap = "1"
base64 = "0.23"
binrw = "0.13"
bytes = "1"
env_logger = "0.11"
futures = "0.3"
linkme = "0.3"
log = "0.4"
parking_lot = "0.12"
rand = "0.8"
rust-i18n = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_yaml = "0.8"
toml = "0.9"
aho-corasick = "1"
ureq = "3.4.0"

ygopro = { version = "0", default-features = false }
ygopro-data = { version = "0", default-features = false }
ygopro-derive = "0"
ygopro-external-server-bridge = "0"
ygopro-handler = { version = "0", default-features = false }

[features]
default = ["zip", "card"]
zip = ["ygopro/zip"]
card = ["ygopro/card"]
