port: 7911
ygopro:
  cwd: /usr/src/app/srvpru/ygopro/
  binary: ./ygopro
  address: 127.0.0.1
  wait_start: 10
plugins:
- room
- player

- stage_recorder
- position_recorder
- lp_recorder

- debugger
- welcome
- version_checker
- delayed_replay
- random_match
- result_report
- telescreen
- reconnect
- newspeak
- room_list
- dialogue
- must_start